services:
  db:
    image: postgres:18.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      - NODE_ENV=development
    command: pnpm run dev 

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
    command: pnpm exec ng serve --host 0.0.0.0

volumes:
  postgres_data:

