INSERT INTO refs.input_type(name) VALUES
  ('input'),
  ('radio'),
  ('checkbox'),
  ('aroma_selector')
  ON CONFLICT (name) DO NOTHING
  ;

INSERT INTO refs.category(default_name, position, default_description) VALUES
  ('sight',1,'visual description of the wine'),
  ('nose',2,'olfactory description of the wine'),
  ('palate',3,'gustatory  description of the wine'),
  ('rating',4,'overall appreciation of the wine')
  ON CONFLICT (default_name) DO NOTHING
  ;

INSERT INTO refs.criterion(category_id, input_type_id, default_name, position, default_description) VALUES
-- VISUAL CRITERIONS
  ((SELECT id FROM refs.category WHERE default_name = 'sight'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'clarity', 1, 'clarity of the wine'),
  ((SELECT id FROM refs.category WHERE default_name = 'sight'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'concentration', 2, 'concentration of color in the wine'),
  ((SELECT id FROM refs.category WHERE default_name = 'sight'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'primary color', 3, 'color that you perceive when looking at the heart of the wine'),
  ((SELECT id FROM refs.category WHERE default_name = 'sight'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'secondary color', 4, 'color that you perceive when looking at the edges of the wine'),
  ((SELECT id FROM refs.category WHERE default_name = 'sight'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'rim variation', 5, 'length of color gradient for center to edges of the wine'),
  ((SELECT id FROM refs.category WHERE default_name = 'sight'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'tearing', 6, 'thickness of the tears of the wine'),
  ((SELECT id FROM refs.category WHERE default_name = 'sight'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'staining', 7, 'color of the tears of the wine'),
  ((SELECT id FROM refs.category WHERE default_name = 'sight'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'sediments', 9, 'amount of sediments at the bottom of the wine'),
  ((SELECT id FROM refs.category WHERE default_name = 'sight'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'effervescence', 8, 'amount of gas bubbles in the wine'),
  -- OLFACTORY CRITERIONS
  ((SELECT id FROM refs.category WHERE default_name = 'nose'), (SELECT id FROM refs.input_type WHERE name = 'checkbox'), 'faults', 2, 'noticeable faults in the wine if any'),
  ((SELECT id FROM refs.category WHERE default_name = 'nose'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'intensity', 1, 'intensity of the aromas'),
  ((SELECT id FROM refs.category WHERE default_name = 'nose'), (SELECT id FROM refs.input_type WHERE name = 'aroma_selector'), 'aromas', 3, 'noticeable aromas in the wine'),
  -- GUSTATORY CRITERIONS
  ((SELECT id FROM refs.category WHERE default_name = 'palate'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'sweetness', 1, 'how sweet the wine tastes'),
  ((SELECT id FROM refs.category WHERE default_name = 'palate'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'acidity', 2, 'how acidic of the wine tastes'),
  ((SELECT id FROM refs.category WHERE default_name = 'palate'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'alcohol', 3, 'how rich in alcohol the wine tastes'),
  ((SELECT id FROM refs.category WHERE default_name = 'palate'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'tannins volume', 4, 'how present the tannins are in the wine'),
  ((SELECT id FROM refs.category WHERE default_name = 'palate'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'tannins texture', 5, 'how the tannins feel on the touch of the tongue and lips'),
  ((SELECT id FROM refs.category WHERE default_name = 'palate'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'body', 7, 'how rich the wine tastes'),
  ((SELECT id FROM refs.category WHERE default_name = 'palate'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'bitterness', 6, 'how bitter the wine tastes'),
  ((SELECT id FROM refs.category WHERE default_name = 'palate'), (SELECT id FROM refs.input_type WHERE name = 'aroma_selector'), 'flavors', 8, 'noticeable flavors in the wine'),
  ((SELECT id FROM refs.category WHERE default_name = 'palate'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'finish', 9, 'how long the wine lasts in the mouth'),
  -- RATING CRITERIONS
  ((SELECT id FROM refs.category WHERE default_name = 'rating'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'score',1,  'how much do you appreciate the wine'),
  ((SELECT id FROM refs.category WHERE default_name = 'rating'), (SELECT id FROM refs.input_type WHERE name = 'radio'), 'heart stroke', 2, 'whether you have a crush on the wine'),
  ((SELECT id FROM refs.category WHERE default_name = 'rating'), (SELECT id FROM refs.input_type WHERE name = 'input'), 'comment', 3, 'your comment about the wine')
  ON CONFLICT (default_name) DO NOTHING
;

INSERT INTO refs.criterion_value(criterion_id, value, default_label) VALUES
  ((SELECT id FROM refs.criterion WHERE default_name = 'clarity'),1,'clear'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'clarity'),2,'hazy'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'clarity'),3,'cloudy'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'concentration'),1,'translucent'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'concentration'),2,'pale'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'concentration'),3,'medium minus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'concentration'),4,'medium'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'concentration'),5,'medium plus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'concentration'),6,'deep'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'concentration'),7,'opaque'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'primary color'),1,'water'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'primary color'),2,'straw'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'primary color'),3,'yellow'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'primary color'),4,'gold'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'primary color'),5,'purple'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'primary color'),6,'ruby'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'primary color'),7,'garnet'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'secondary color'),1,'silver'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'secondary color'),2,'green'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'secondary color'),3,'gold'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'secondary color'),4,'copper'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'secondary color'),5,'brown'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'secondary color'),6,'garnet'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'secondary color'),7,'orange'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'secondary color'),8,'ruby'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'secondary color'),9,'magenta'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'secondary color'),10,'blue'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'rim variation'),1,'yes'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'rim variation'),2,'no'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tearing'),1,'light'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tearing'),2,'medium minus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tearing'),3,'medium'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tearing'),4,'medium plus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tearing'),5,'heavy'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'staining'),1,'none'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'staining'),2,'light'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'staining'),3,'medium minus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'staining'),4,'medium'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'staining'),5,'medium plus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'staining'),6,'heavy'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'effervescence'),1,'still'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'effervescence'),2,'semi-sparkling'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'effervescence'),3,'sparkling'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'sediments'),1,'yes'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'sediments'),2,'no'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'faults'),1,'cork taint'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'faults'),2,'reduction'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'faults'),3,'oxydation'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'faults'),4,'brettanomyces'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'faults'),5,'volatile acidity'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'faults'),6,'sulfur excess'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'intensity'),1,'delicate'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'intensity'),2,'medium minus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'intensity'),3,'medium'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'intensity'),4,'medium plus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'intensity'),5,'powerful'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'sweetness'),1,'bone dry'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'sweetness'),2,'dry'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'sweetness'),3,'off-dry'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'sweetness'),4,'medium-sweet'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'sweetness'),5,'sweet'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'sweetness'),6,'lusciously sweet'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'acidity'),1,'low'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'acidity'),2,'medium minus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'acidity'),3,'medium'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'acidity'),4,'medium plus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'acidity'),5,'high'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'alcohol'),1,'low'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'alcohol'),2,'medium minus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'alcohol'),3,'medium'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'alcohol'),4,'medium plus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'alcohol'),5,'high'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'body'),1,'light'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'body'),2,'medium minus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'body'),3,'medium'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'body'),4,'medium plus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'body'),5,'full'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'bitterness'),1,'yes'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'bitterness'),2,'no'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tannins volume'),1,'low'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tannins volume'),2,'medium minus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tannins volume'),3,'medium'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tannins volume'),4,'medium plus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tannins volume'),5,'high'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tannins texture'),1,'silky'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tannins texture'),2,'soft'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tannins texture'),3,'gritty'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tannins texture'),4,'coarse'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tannins texture'),5,'rough'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tannins texture'),6,'stalky'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'tannins texture'),7,'hard'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'finish'),1,'short'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'finish'),2,'medium minus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'finish'),3,'medium'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'finish'),4,'medium plus'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'finish'),5,'long'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'score'),1,'1'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'score'),2,'2'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'score'),3,'3'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'score'),4,'4'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'score'),5,'5'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'heart stroke'),1,'yes'),
  ((SELECT id FROM refs.criterion WHERE default_name = 'heart stroke'),2,'no')
  ON CONFLICT (criterion_id, value, default_label) DO NOTHING
  ;

INSERT INTO refs.aroma_family(default_name) VALUES
  ('fruity aromas'),
  ('floral aromas'),
	('vegetal aromas'),
	('spicy aromas'),
	('candy aromas'),
	('toasty aromas'),
	('mineral aromas'),
	('animal aromas'),
	('milky aromas'),
	('yeasty aromas')
	ON CONFLICT (default_name) DO NOTHING
;

INSERT INTO refs.aroma_subfamily(aroma_family_id,default_name) VALUES
	((SELECT id FROM refs.aroma_family WHERE default_name = 'fruity aromas'),'red fruits'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'fruity aromas'),'pip fruits'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'fruity aromas'),'stone fruits'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'fruity aromas'),'citrus fruits'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'fruity aromas'),'tropical fruits'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'fruity aromas'),'dried fruits'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'fruity aromas'),'jammy fruits'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'vegetal aromas'),'herbs'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'vegetal aromas'),'woods'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'vegetal aromas'),'vegetables'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'vegetal aromas'),'other plants'),
  ((SELECT id FROM refs.aroma_family WHERE default_name = 'fruity aromas'),'fruity aromas'),
  ((SELECT id FROM refs.aroma_family WHERE default_name = 'floral aromas'),'floral aromas'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'vegetal aromas'),'vegetal aromas'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'spicy aromas'),'spicy aromas'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'candy aromas'),'candy aromas'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'toasty aromas'),'toasty aromas'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'mineral aromas'),'mineral aromas'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'animal aromas'),'animal aromas'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'milky aromas'),'milky aromas'),
	((SELECT id FROM refs.aroma_family WHERE default_name = 'yeasty aromas'),'yeasty aromas')
	ON CONFLICT (default_name) DO NOTHING
;

INSERT INTO refs.aroma(aroma_subfamily_id,default_name) VALUES
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'red fruits'),'raspberries'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'red fruits'),'blackcurrants'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'red fruits'),'strawberries'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'red fruits'),'blueberries'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'pip fruits'),'apples'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'pip fruits'),'pears'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'pip fruits'),'quinces'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'stone fruits'),'cherries'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'stone fruits'),'plums'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'stone fruits'),'apricots'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'stone fruits'),'peaches'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'citrus fruits'),'lemons'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'citrus fruits'),'oranges'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'citrus fruits'),'mandarines'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'citrus fruits'),'grapefruits'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'citrus fruits'),'lemon zests'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'citrus fruits'),'orange zests'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'tropical fruits'),'pineapples'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'tropical fruits'),'mangos'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'tropical fruits'),'bananas'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'tropical fruits'),'guavas'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'tropical fruits'),'passion fruits'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'tropical fruits'),'lychees'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'dried fruits'),'almonds'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'dried fruits'),'hazelnuts'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'dried fruits'),'walnuts'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'dried fruits'),'figs'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'dried fruits'),'dates'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'dried fruits'),'prunes'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'jammy fruits'),'marmelade'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'jammy fruits'),'strawberry jam'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'jammy fruits'),'cherry jam'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'jammy fruits'),'red fruits jam'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'floral aromas'),'violets'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'floral aromas'),'roses'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'floral aromas'),'honeysuckle'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'floral aromas'),'jamsin'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'floral aromas'),'orange blossoms'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'floral aromas'),'lime'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'floral aromas'),'acacia blossoms'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'floral aromas'),'lavender'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'herbs'),'cut grass'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'herbs'),'ferns'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'herbs'),'mint'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'herbs'),'verbena'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'herbs'),'thyme'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'herbs'),'dill'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'herbs'),'eucalyptus'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'woods'),'oak'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'woods'),'pine'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'woods'),'cedar'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'vegetables'),'bell pepper'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'vegetables'),'asparagus'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'vegetables'),'tomatos'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'vegetables'),'fennel'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'other plants'),'hay'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'other plants'),'tobacco'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'other plants'),'green tea'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'other plants'),'black tea'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'other plants'),'undergrowths'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'other plants'),'mushrooms'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'other plants'),'truffles'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'other plants'),'humus'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'spicy aromas'),'vanilla'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'spicy aromas'),'black pepper'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'spicy aromas'),'white pepper'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'spicy aromas'),'cinnamon'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'spicy aromas'),'liquorice'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'spicy aromas'),'nutmeg'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'spicy aromas'),'cloves'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'spicy aromas'),'star anis'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'spicy aromas'),'curry'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'candy aromas'),'caramel'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'candy aromas'),'honey'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'candy aromas'),'almond paste'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'toasty aromas'),'tar'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'toasty aromas'),'smoked'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'toasty aromas'),'coffee'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'toasty aromas'),'fireplace'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'toasty aromas'),'chocolate'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'toasty aromas'),'grilled'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'toasty aromas'),'toasted'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'mineral aromas'),'flint'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'mineral aromas'),'chalk'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'mineral aromas'),'petrol'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'animal aromas'),'leather'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'animal aromas'),'musk'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'milky aromas'),'butter'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'milky aromas'),'yogurt'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'yeasty aromas'),'yeasts'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'yeasty aromas'),'bread'),
	((SELECT id FROM refs.aroma_subfamily WHERE default_name = 'yeasty aromas'),'brioche')
	ON CONFLICT (default_name) DO NOTHING
	;

INSERT INTO refs.criterion_aroma (criterion_id, aroma_id)
	SELECT (SELECT id FROM refs.criterion WHERE default_name = 'aromas'), id FROM refs.aroma
	;

	INSERT INTO refs.criterion_aroma (criterion_id, aroma_id)
	SELECT (SELECT id FROM refs.criterion WHERE default_name = 'flavors'), id FROM refs.aroma
	;
