INSERT INTO wines.color (default_name) VALUES
	('red'),
	('white'),
	('rosé'),
	('orange'),
	('yellow')
	ON CONFLIT (default_name) DO NOTHING;

INSERT INTO wines.country (default_name, iso_code) VALUES
	('Afghanistan','AF'),
	('Albania','AL'),
	('Algeria','DZ'),
	('American Samoa','AS'),
	('Andorra','AD'),
	('Angola','AO'),
	('Anguilla','AI'),
	('Antarctica','AQ'),
	('Antigua and Barbuda','AG'),
	('Argentina','AR'),
	('Armenia','AM'),
	('Aruba','AW'),
	('Australia','AU'),
	('Austria','AT'),
	('Azerbaijan','AZ'),
	('Bahamas (the)','BS'),
	('Bahrain','BH'),
	('Bangladesh','BD'),
	('Barbados','BB'),
	('Belarus','BY'),
	('Belgium','BE'),
	('Belize','BZ'),
	('Benin','BJ'),
	('Bermuda','BM'),
	('Bhutan','BT'),
	('Bolivia (Plurinational State of)','BO'),
	('Bonaire, Sint Eustatius and Saba','BQ'),
	('Bosnia and Herzegovina','BA'),
	('Botswana','BW'),
	('Bouvet Island','BV'),
	('Brazil','BR'),
	('British Indian Ocean Territory (the)','IO'),
	('Brunei Darussalam','BN'),
	('Bulgaria','BG'),
	('Burkina Faso','BF'),
	('Burundi','BI'),
	('Cabo Verde','CV'),
	('Cambodia','KH'),
	('Cameroon','CM'),
	('Canada','CA'),
	('Cayman Islands (the)','KY'),
	('Central African Republic (the)','CF'),
	('Chad','TD'),
	('Chile','CL'),
	('China','CN'),
	('Christmas Island','CX'),
	('Cocos (Keeling) Islands (the)','CC'),
	('Colombia','CO'),
	('Comoros (the)','KM'),
	('Congo (the Democratic Republic of the)','CD'),
	('Congo (the)','CG'),
	('Cook Islands (the)','CK'),
	('Costa Rica','CR'),
	('Croatia','HR'),
	('Cuba','CU'),
	('Curaçao','CW'),
	('Cyprus','CY'),
	('Czechia','CZ'),
	('Côte d''Ivoire','CI'),
	('Denmark','DK'),
	('Djibouti','DJ'),
	('Dominica','DM'),
	('Dominican Republic (the)','DO'),
	('Ecuador','EC'),
	('Egypt','EG'),
	('El Salvador','SV'),
	('Equatorial Guinea','GQ'),
	('Eritrea','ER'),
	('Estonia','EE'),
	('Eswatini','SZ'),
	('Ethiopia','ET'),
	('Falkland Islands (the) [Malvinas]','FK'),
	('Faroe Islands (the)','FO'),
	('Fiji','FJ'),
	('Finland','FI'),
	('France','FR'),
	('French Guiana','GF'),
	('French Polynesia','PF'),
	('French Southern Territories (the)','TF'),
	('Gabon','GA'),
	('Gambia (the)','GM'),
	('Georgia','GE'),
	('Germany','DE'),
	('Ghana','GH'),
	('Gibraltar','GI'),
	('Greece','GR'),
	('Greenland','GL'),
	('Grenada','GD'),
	('Guadeloupe','GP'),
	('Guam','GU'),
	('Guatemala','GT'),
	('Guernsey','GG'),
	('Guinea','GN'),
	('Guinea-Bissau','GW'),
	('Guyana','GY'),
	('Haiti','HT'),
	('Heard Island and McDonald Islands','HM'),
	('Holy See (the)','VA'),
	('Honduras','HN'),
	('Hong Kong','HK'),
	('Hungary','HU'),
	('Iceland','IS'),
	('India','IN'),
	('Indonesia','ID'),
	('Iran (Islamic Republic of)','IR'),
	('Iraq','IQ'),
	('Ireland','IE'),
	('Isle of Man','IM'),
	('Israel','IL'),
	('Italy','IT'),
	('Jamaica','JM'),
	('Japan','JP'),
	('Jersey','JE'),
	('Jordan','JO'),
	('Kazakhstan','KZ'),
	('Kenya','KE'),
	('Kiribati','KI'),
	('Korea (the Democratic People''s Republic of)','KP'),
	('Korea (the Republic of)','KR'),
	('Kuwait','KW'),
	('Kyrgyzstan','KG'),
	('Lao People''s Democratic Republic (the)','LA'),
	('Latvia','LV'),
	('Lebanon','LB'),
	('Lesotho','LS'),
	('Liberia','LR'),
	('Libya','LY'),
	('Liechtenstein','LI'),
	('Lithuania','LT'),
	('Luxembourg','LU'),
	('Macao','MO'),
	('Madagascar','MG'),
	('Malawi','MW'),
	('Malaysia','MY'),
	('Maldives','MV'),
	('Mali','ML'),
	('Malta','MT'),
	('Marshall Islands (the)','MH'),
	('Martinique','MQ'),
	('Mauritania','MR'),
	('Mauritius','MU'),
	('Mayotte','YT'),
	('Mexico','MX'),
	('Micronesia (Federated States of)','FM'),
	('Moldova (the Republic of)','MD'),
	('Monaco','MC'),
	('Mongolia','MN'),
	('Montenegro','ME'),
	('Montserrat','MS'),
	('Morocco','MA'),
	('Mozambique','MZ'),
	('Myanmar','MM'),
	('Namibia','NA'),
	('Nauru','NR'),
	('Nepal','NP'),
	('Netherlands (the)','NL'),
	('New Caledonia','NC'),
	('New Zealand','NZ'),
	('Nicaragua','NI'),
	('Niger (the)','NE'),
	('Nigeria','NG'),
	('Niue','NU'),
	('Norfolk Island','NF'),
	('Northern Mariana Islands (the)','MP'),
	('Norway','NO'),
	('Oman','OM'),
	('Pakistan','PK'),
	('Palau','PW'),
	('Palestine, State of','PS'),
	('Panama','PA'),
	('Papua New Guinea','PG'),
	('Paraguay','PY'),
	('Peru','PE'),
	('Philippines (the)','PH'),
	('Pitcairn','PN'),
	('Poland','PL'),
	('Portugal','PT'),
	('Puerto Rico','PR'),
	('Qatar','QA'),
	('Republic of North Macedonia','MK'),
	('Romania','RO'),
	('Russian Federation (the)','RU'),
	('Rwanda','RW'),
	('Réunion','RE'),
	('Saint Barthélemy','BL'),
	('Saint Helena, Ascension and Tristan da Cunha','SH'),
	('Saint Kitts and Nevis','KN'),
	('Saint Lucia','LC'),
	('Saint Martin (French part)','MF'),
	('Saint Pierre and Miquelon','PM'),
	('Saint Vincent and the Grenadines','VC'),
	('Samoa','WS'),
	('San Marino','SM'),
	('Sao Tome and Principe','ST'),
	('Saudi Arabia','SA'),
	('Senegal','SN'),
	('Serbia','RS'),
	('Seychelles','SC'),
	('Sierra Leone','SL'),
	('Singapore','SG'),
	('Sint Maarten (Dutch part)','SX'),
	('Slovakia','SK'),
	('Slovenia','SI'),
	('Solomon Islands','SB'),
	('Somalia','SO'),
	('South Africa','ZA'),
	('South Georgia and the South Sandwich Islands','GS'),
	('South Sudan','SS'),
	('Spain','ES'),
	('Sri Lanka','LK'),
	('Sudan (the)','SD'),
	('Suriname','SR'),
	('Svalbard and Jan Mayen','SJ'),
	('Sweden','SE'),
	('Switzerland','CH'),
	('Syrian Arab Republic','SY'),
	('Taiwan (Province of China)','TW'),
	('Tajikistan','TJ'),
	('Tanzania, United Republic of','TZ'),
	('Thailand','TH'),
	('Timor-Leste','TL'),
	('Togo','TG'),
	('Tokelau','TK'),
	('Tonga','TO'),
	('Trinidad and Tobago','TT'),
	('Tunisia','TN'),
	('Turkey','TR'),
	('Turkmenistan','TM'),
	('Turks and Caicos Islands (the)','TC'),
	('Tuvalu','TV'),
	('Uganda','UG'),
	('Ukraine','UA'),
	('United Arab Emirates (the)','AE'),
	('United Kingdom of Great Britain and Northern Ireland (the)','GB'),
	('United States Minor Outlying Islands (the)','UM'),
	('United States of America (the)','US'),
	('Uruguay','UY'),
	('Uzbekistan','UZ'),
	('Vanuatu','VU'),
	('Venezuela (Bolivarian Republic of)','VE'),
	('Viet Nam','VN'),
	('Virgin Islands (British)','VG'),
	('Virgin Islands (U.S.)','VI'),
	('Wallis and Futuna','WF'),
	('Western Sahara','EH'),
	('Yemen','YE'),
	('Zambia','ZM'),
	('Zimbabwe','ZW'),
	('Åland Islands AX')
ON CONFLICT (iso_code, default_name) DO NOTHING;

INSERT INTO wines.region (country_id,default_name) VALUES
	((SELECT id FROM wines.country WHERE iso_code = 'FR'),'France'),
	((SELECT id FROM wines.country WHERE iso_code = 'FR'),'Alsace'),
	((SELECT id FROM wines.country WHERE iso_code = 'FR'),'Moselle'),
	((SELECT id FROM wines.country WHERE iso_code = 'FR'),'Burgundy'),
	((SELECT id FROM wines.country WHERE iso_code = 'FR'),'Bordeaux'),
	((SELECT id FROM wines.country WHERE iso_code = 'FR'),'Jura'),
	((SELECT id FROM wines.country WHERE iso_code = 'FR'),'Savoie-Bugey'),
	((SELECT id FROM wines.country WHERE iso_code = 'FR'),'Cognac'),
	((SELECT id FROM wines.country WHERE iso_code = 'FR'),'Beaujolais'),
	((SELECT id FROM wines.country WHERE iso_code = 'FR'),'Rhone Valley'),
	((SELECT id FROM wines.country WHERE iso_code = 'FR'),'Loire Valley'),
	((SELECT id FROM wines.country WHERE iso_code = 'FR'),'Corsica'),
	((SELECT id FROM wines.country WHERE iso_code = 'FR'),'Languedoc-Roussillon'),
	((SELECT id FROM wines.country WHERE iso_code = 'FR'),'South West'),
	((SELECT id FROM wines.country WHERE iso_code = 'FR'),'Provence'),
	((SELECT id FROM wines.country WHERE iso_code = 'FR'),'Champagne'),
ON CONFLICT (country_id, default_name) DO NOTHING;

INSERT INTO wines.appellation (region_id, default_name) VALUES
	-- VDF
	((SELECT id FROM wines.region WHERE default_name='France'),'Vin de France'),
	-- regional IGP
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'IGP Atlantique'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'IGP Comté Tolosan'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'IGP Atlantique'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Pays d''Oc'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Terres de Midi'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'IGP Val de Loire'),
	((SELECT id FROM wines.region WHERE default_name='Provence'),'IGP Méditerranée'),
	((SELECT id FROM wines.region WHERE default_name='Corsica'),'IGP Méditerranée'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'IGP Méditerranée'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'IGP Comtés Rhodaniens'),
	-- departmental IGP
	((SELECT id FROM wines.region WHERE default_name='France'),'IGP Calvados'),
	((SELECT id FROM wines.region WHERE default_name='Provence'),'IGP Alpes-de-Haute-Provence'),
	((SELECT id FROM wines.region WHERE default_name='Provence'),'IGP Alpes-Maritimes'),
	((SELECT id FROM wines.region WHERE default_name='Provence'),'IGP Hautes-Alpes'),
	((SELECT id FROM wines.region WHERE default_name='Provence'),'IGP Var'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'IGP Pays des Bouches-du-Rhône'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'IGP Vaucluse'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'IGP Drôme'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'IGP Ardèche'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'IGP Isère'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'IGP Coteaux de l''Ain'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'IGP Saône-et-Loire'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'IGP Yonne'),
	((SELECT id FROM wines.region WHERE default_name='Champagne'),'IGP Haute-Marne'),
	((SELECT id FROM wines.region WHERE default_name='Cognac'),'IGP Charentais'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'IGP Puy-de-Dôme'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'IGP Haute-Vienne'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'IGP Pays de Brive'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'IGP Périgord'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'IGP Côtes du Lot'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'IGP Landes'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'IGP Gers'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'IGP Aveyron'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Gard'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Pays d''Hérault'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Aude'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Côtes Catalanes'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Ariège'),
	((SELECT id FROM wines.region WHERE default_name='Corsica'),'IGP Île de Beauté'),
	-- specific areas IGP
	((SELECT id FROM wines.region WHERE default_name='South West'),'IGP Agenais'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'IGP Alpilles'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Cévennes'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'IGP Collines Rhodaniennes'),
	((SELECT id FROM wines.region WHERE default_name='Champagne'),'IGP Coteaux de Coiffy'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Coteaux d''Ensérune'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Coteaux de Béziers'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'IGP Coteaux de l''Auxois'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'IGP Coteaux de Glanes'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Coteaux de Peyriac'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'IGP Coteaux de Tannay'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'IGP Coteaux des Baronnies'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Coteaux du Pont du Gard'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'IGP Coteaux du Cher et de l''Arnon'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Côte Vermeille'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'IGP Côtes de Gascogne'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'IGP Côtes de la Charité'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Côtes de Thau'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Côtes de Thongue'),
	((SELECT id FROM wines.region WHERE default_name='Moselle'),'IGP Côtes de Meuse'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'IGP Côtes du Tarn'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'IGP Côtes du Tarn'),
	((SELECT id FROM wines.region WHERE default_name='Jura'),'IGP Franche-Comté'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Haute Vallée de l''Aude'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Haute Vallée de l''Orb'),
	((SELECT id FROM wines.region WHERE default_name='France'),'IGP Île-de-France'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'IGP Lavilledieu'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Le Pays Cathare'),
	((SELECT id FROM wines.region WHERE default_name='Moselle'),'IGP Lorraine'),
	((SELECT id FROM wines.region WHERE default_name='Provence'),'IGP Maures'),
	((SELECT id FROM wines.region WHERE default_name='Provence'),'IGP Mont Caume'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Saint-Guilhem-le-Désert'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'IGP Sainte-Marie-la-Blanche'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'IGP Thézac-Perricard'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'IGP Urfé'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Vallée du Paradis'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'(IGP Vallée du Torgan'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'IGP Vicomté d''Aumelas'),
	((SELECT id FROM wines.region WHERE default_name='Savoie-Bugey'),'IGP Vin des Allobroges')
	-- AOC
	((SELECT id FROM wines.region WHERE default_name='Cognac'),'Pineau des Charentes'),
	((SELECT id FROM wines.region WHERE default_name='Corsica'),'Ajaccio'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Aloxe-Corton'),
	((SELECT id FROM wines.region WHERE default_name='Alsace'),'Alsace'),
	((SELECT id FROM wines.region WHERE default_name='Alsace'),'Alsace grand cru'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Anjou'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Anjou Coteaux de la Loire'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Anjou Villages'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Anjou Villages Brissac'),
	((SELECT id FROM wines.region WHERE default_name='Jura'),'Arbois'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Auxey-Duresses'),
	((SELECT id FROM wines.region WHERE default_name='Provence'),'Bandol'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Banyuls'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Banyuls grand cru'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Barsac'),
	((SELECT id FROM wines.region WHERE default_name='Bourgundy'),'Bâtard-Montrachet'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Béarn'),
	((SELECT id FROM wines.region WHERE default_name='Beaujolais'),'Beaujolais'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Beaumes de Venise'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Beaune'),
	((SELECT id FROM wines.region WHERE default_name='Provence'),'Bellet ou Vin de Bellet'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Bergerac'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Bienvenues Bâtard-Montrachet'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Blagny'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Blaye'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Bonnes-Mares'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Bonnezeaux'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Bordeaux'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Bordeaux Supérieur'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Bourgogne'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Bourgogne Aligoté'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Bourgogne Mousseux'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Bourgogne Passe-Tout-Grains'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Bourgueil'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Bouzeron'),
	((SELECT id FROM wines.region WHERE default_name='Beaujolais'),'Brouilly'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Brulhois'),
	((SELECT id FROM wines.region WHERE default_name='Savoie-Bugey'),'Bugey'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Buzet'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Cabardès'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Cabernet d’Anjou'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Cabernet de Saumur'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Cadillac'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Cahors'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Canon-Fronsac'),
	((SELECT id FROM wines.region WHERE default_name='Provence'),'Cassis'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Cérons'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Chablis'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Chablis Grand Cru'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Chambertin'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Chambertin-Clos-de-Bèze'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Chambolle-Musigny'),
	((SELECT id FROM wines.region WHERE default_name='Champagne'),'Champagne'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Chapelle-Chambertin'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Charlemagne'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Charmes-Chambertin'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Chassagne-Montrachet'),
	((SELECT id FROM wines.region WHERE default_name='Jura'),'Château-Chalon'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Château-Grillet'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Châteaumeillant'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Châteauneuf-du-Pape'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Chatillon-en-Diois'),
	((SELECT id FROM wines.region WHERE default_name='Beaujolais'),'Chénas'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Chevalier-Montrachet'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Cheverny'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Chinon'),
	((SELECT id FROM wines.region WHERE default_name='Beaujolais'),'Chiroubles'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Chorey-Lès-Beaune'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Clairette de Bellegarde'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Clairette du Languedoc'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Clairette de Die'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Clos de la Roche'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Clos de Tart'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Clos de Vougeot ou Clos Vougeot'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Clos des Lambrays'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Clos Saint-Denis'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Collioure'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Condrieu'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Corbières'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Corbières-Boutenac'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Cornas'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Corton'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Corton-Charlemagne'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Costières de Nîmes'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Côte de Beaune'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Côte de Beaune-Villages'),
	((SELECT id FROM wines.region WHERE default_name='Beaujolais'),'Côte de Brouilly'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Côte de Nuits-Villages'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'-Jura-Savoie Côte Roannaise'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Côte Rôtie'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Coteaux Bourguignons'),
	((SELECT id FROM wines.region WHERE default_name='Champagne'),'Côteaux champenois'),
	((SELECT id FROM wines.region WHERE default_name='Provence'),'Coteaux d’Aix-en-Provence'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Coteaux d’Ancenis'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Coteaux de Die'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Coteaux de l’Aubance'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Coteaux de Saumur'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Coteaux du Giennois'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Coteaux du Layon'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Coteaux du Loir'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Coteaux du Lyonnais'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Coteaux du Quercy'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Côteaux du Vendômois'),
	((SELECT id FROM wines.region WHERE default_name='Provence'),'Coteaux varois en Provence'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Côtes d''Auvergne'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Côtes de Bergerac'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Côtes de Blaye'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Côtes de Bordeaux'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Côtes de Bordeaux Saint-Macaire'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Côtes de Bourg, Bourg, Bourgeais'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Côtes de Duras'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Côtes de Millau'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Côtes de Montravel'),
	((SELECT id FROM wines.region WHERE default_name='Provence'),'Côtes de Provence'),
	((SELECT id FROM wines.region WHERE default_name='Moselle'),'Côtes de Toul'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Côtes du Forez'),
	((SELECT id FROM wines.region WHERE default_name='Jura'),'Côtes du Jura'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Côtes du Marmandais'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Côtes du Roussillon'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Côtes du Roussillon Villages'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Côtes du Vivarais'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Côtes du Rhone'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Côtes du Rhone Villages'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Cour-Cheverny'),
	((SELECT id FROM wines.region WHERE default_name='Alsace'),'Crémant d’Alsace'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Crémant de Bordeaux'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Crémant de Bourgogne'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Crémant de Die'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Crémant de Limoux'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Crémant de Loire'),
	((SELECT id FROM wines.region WHERE default_name='Jura'),'Crémant du Jura'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Criots-Bâtard-Montrachet'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Crozes-Hermitage'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Duché d''Uzès'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Echezeaux'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Entraygues et le Fel'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Entre-Deux-Mers'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Estaing'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Faugères'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Fiefs Vendéens'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Fitou'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Fixin'),
	((SELECT id FROM wines.region WHERE default_name='Beaujolais'),'Fleurie'),
	((SELECT id FROM wines.region WHERE default_name='Armagnac Floc de Gascogne'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Fronsac'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Fronton'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Gaillac'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Gaillac Premières Côtes'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Gevrey-Chambertin'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Gigondas'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Givry'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Grand Roussillon'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Grands-Echezeaux'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Graves'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Graves de Vayres'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Graves Supérieures'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Grignan-les-Adhémar'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Griotte-Chambertin'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Gros Plant du Pays Nantais'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Haut-Médoc'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Haut-Montravel'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Haut-Poitou'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Hermitage'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Irancy'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Irouléguy'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Jasnières'),
	((SELECT id FROM wines.region WHERE default_name='Beaujolais'),'Juliénas'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Jurançon'),
	((SELECT id FROM wines.region WHERE default_name='Jura'),'L’Etoile'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'La Grande Rue'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'La Romanée'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'La Tâche'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Ladoix'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Lalande-de-Pomerol'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Languedoc'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Latricières-Chambertin'),
	((SELECT id FROM wines.region WHERE default_name='Provence'),'Les Baux de Provence'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Limoux'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Lirac'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Listrac-Médoc'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Loupiac'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Luberon'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Lussac-Saint-Emilion'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Mâcon'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Macvin du Jura'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Madiran'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Malepère'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Maranges'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Marcillac'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Margaux'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Marsannay'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Maury'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Mazis-Chambertin'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Mazoyères-Chambertin'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Médoc'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Menetou-Salon'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Mercurey'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Meursault'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Minervois'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Minervois-La Livinière'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Monbazillac'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Montagne-Saint-Emilion'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Montagny'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Monthélie'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Montlouis-sur-Loire'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Montrachet'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Montravel'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Morey-Saint-Denis'),
	((SELECT id FROM wines.region WHERE default_name='Beaujolais'),'Morgon'),
	((SELECT id FROM wines.region WHERE default_name='Moselle'),'Moselle'),
	((SELECT id FROM wines.region WHERE default_name='Beaujolais'),'Moulin-à-Vent'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Moulis ou Moulis-en-Médoc'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Muscadet'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Muscadet Coteaux de la Loire'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Muscadet Côtes de Grandlieu'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Muscadet Sèvre et Maine'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Muscat de Beaumes-de-Venise'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Muscat de Frontignan ou Frontignan ou Vin de Frontignan'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Muscat de Lunel'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Muscat de Mireval'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Muscat de Risevaltes'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Muscat de Saint-Jean-de-Minervois'),
	((SELECT id FROM wines.region WHERE default_name='Corsica'),'Muscat du Cap Corse'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Musigny'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Nuits-Saint-Georges'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Orléans'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Orléans-Cléry'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Pacherenc du Vic-Bilh'),
	((SELECT id FROM wines.region WHERE default_name='Provence'),'Palette'),
	((SELECT id FROM wines.region WHERE default_name='Corsica'),'Patrimonio'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Pauillac'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Pécharmant'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Pernand-Vergelesses'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Pessac-Léognan'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Petit Chablis'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Picpoul de Pinet'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Pierrevert'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Pomerol'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Pommard'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Pouilly-Fuissé'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Pouilly-Fumé ou Blanc fumé de Pouilly'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Pouilly-Loché'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Pouilly-sur-Loire'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Pouilly-Vinzelles'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Premières Côtes de Bordeaux'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Puisseguin-Saint-Emilion'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Puligny-Montrachet'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Quarts de Chaume'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Quincy'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Rasteau'),
	((SELECT id FROM wines.region WHERE default_name='Beaujolais'),'Régnié'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Reuilly'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Richebourg'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Rivesaltes'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Romanée-Conti'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Romanée-Saint-Vivant'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Rosé d’Anjou'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Rosé de Loire'),
	((SELECT id FROM wines.region WHERE default_name='Champagne'),'Rosé des Riceys'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Rosette'),
	((SELECT id FROM wines.region WHERE default_name='Savoie-Bugey'),'Rousette du Bugey'),
	((SELECT id FROM wines.region WHERE default_name='Savoie-Bugey'),'Roussette de Savoie'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Ruchottes-Chambertin'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Rully'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Saint-Bris'),
	((SELECT id FROM wines.region WHERE default_name='Languedoc-Roussillon'),'Saint-Chinian'),
	((SELECT id FROM wines.region WHERE default_name='Beaujolais'),'Saint-Amour'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Saint-Aubin'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Sainte-Croix-du-Mont'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Sainte-Foy-Bordeaux'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Saint-Emilion'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Saint-Emilion Grand Cru'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Saint-Estèphe'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Saint-Georges-Saint-Emilion'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Saint-Joseph'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Saint-Julien'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Saint-Mont'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Saint-Nicolas-de-Bourgueil'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Saint-Péray'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Saint-Pourçain'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Saint-Romain'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Saint-Sardos'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Saint-Véran'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Sancerre'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Santenay'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Saumur'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Saumur-Champigny'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Saussignac'),
	((SELECT id FROM wines.region WHERE default_name='Bordeaux'),'Sauternes'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Savennières'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Savennières Coulée de Serrant'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Savennières Roche aux Moines'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Savigny-lès-Beaune'),
	((SELECT id FROM wines.region WHERE default_name='Savoie-Bugey'),'Seyssel'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Tavel'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Touraine'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Touraine Noble Joué'),
	((SELECT id FROM wines.region WHERE default_name='South West'),'Tursan'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Vacqueyras'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Valençay'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Ventoux'),
	((SELECT id FROM wines.region WHERE default_name='Corsica'),'Vin de Corse ou Corse'),
	((SELECT id FROM wines.region WHERE default_name='Savoie-Bugey'),'Vin de Savoie ou Savoie'),
	((SELECT id FROM wines.region WHERE default_name='Rhone Valley'),'Vinsobres'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Viré-Clessé'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Volnay'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Vosne-Romanée'),
	((SELECT id FROM wines.region WHERE default_name='Burgundy'),'Vougeot'),
	((SELECT id FROM wines.region WHERE default_name='Loire Valley'),'Vouvray')
ON CONFLICT (region_id, default_name) DO NOTHING;
